### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by willsilvano** [eric-hansen/vscode-docker-phpunit#1]
Hi.
I'm trying to run on Windows and get this error:

`Container: mycontainer.com`
`Command: /var/www/app/vendor/bin/phpunit --filter it_can_delete_todo d:\code\php\myapp\tests\Feature\Todos\TodoFeatureTest.php.`

`Cannot open file d:/code/php/myapp/tests/Feature/Todos/TodoFeatureTest.php`

**Comment by eric-hansen** [comment]
Sorry for the delay in response.

I don't run this on Windows so I can't confirm a fix, but what I will do is change the directory separator and if you wouldn't mind trying it.  Shouldn't take long for me to make this fix.

**Comment by willsilvano** [comment]
@eric-hansen Sure man. How can I do that?

**Comment by willsilvano** [comment]
Still not working now.

**Comment by eric-hansen** [comment]
Right, I never pushed up any changes.  Having an interesting time trying to determine the directory separator to use.  So been digging through the API and such for VSCode.

**Comment by eric-hansen** [comment]
So, here's the thing with this.

I don't use Windows, and the command looks correct.  I am not sure where/what is generating the error "Cannot open file d:/code/php/myapp/tests/Feature/Todos/TodoFeatureTest.php" but would need you to verify this file exists.
